/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-10-24 15:23:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class credentials_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\t\r\n");
      out.write("\r\n");

    String usershow = null;
    String userpg = null;
    String logshow = null;
    String logpg = null;
    
    if(session.getAttribute("userId") != null)
    {
        usershow = "Welcome " + session.getAttribute("userId").toString();
        userpg = "#";
        logshow = "Logoff";
        logpg = "logoff";
        //response.sendRedirect("login_aboutus.jsp");
    }
    else
    {
        usershow = "Register";
        userpg = "register";        
        logshow = "Login";
        logpg = "login";        
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<title>Credentials</title>\r\n");
      out.write("<link href=\"default.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 String n = request.getParameter("name");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t<div id=\"logo\">\r\n");
      out.write("\t\t<h1><a href=\"#\">Big-Sensor-Cloud Infrastructure</a></h1>\r\n");
      out.write("\t\t<h2>By <a href=\"http://www.nodethirtythree.com/\">SIT, IIT, Kharagpur</a> <a href=\"http://www.freecsstemplates.org/\"></a></h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<marquee><b><font size = \"4\" color = \"red\" face=\"Lucida\"><i>Big-Sensor-Cloud: A paradigm shift from traditional WSNs</i></font></b></marquee>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"#\" accesskey=\"1\" title=\"\">Home</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" accesskey=\"2\" title=\"\">Archives</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" accesskey=\"3\" title=\"\">About</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" accesskey=\"4\" title=\"\">Contact</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"logout.jsp\" accesskey=\"4\" title=\"\">Logout</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<div id=\"page\">\r\n");
      out.write("\t<div id=\"bg\">\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<div class=\"post\" style=\"padding-top: 57px;\">\r\n");
      out.write("\t\t\t\t<h2 class=\"title\">Welcome to Big-Sensor-Cloud Infrastructure Version 1.0!</h2>\r\n");
      out.write("\t\t\t\t<h3 class=\"date\">Tuesday, October 28, 2014</h3>\r\n");
      out.write("\t\t\t\t<div style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t<div style=\"box-sizing: border-box; display: inline-block; width: auto; max-width: 480px; background-color: #FFFFFF; border: 2px solid #0361A8; border-radius: 5px; box-shadow: 0px 0px 8px #0361A8; margin: 50px auto auto;\">\r\n");
      out.write("\t\t\t\t\t\t<div style=\"background: #0361A8; border-radius: 5px 5px 0px 0px; padding: 15px;\"><span style=\"font-family: verdana,arial; color: #D4D4D4; font-size: 1.00em; font-weight:bold;\">Get Credentials</span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t <div style=\"background: ; padding: 15px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t <style type=\"text/css\" scoped>\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttd { text-align:left; font-family: verdana,arial; color: #064073; font-size: 1.00em; }\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinput { border: 1px solid #CCCCCC; border-radius: 5px; color: #666666; display: inline-block; font-size: 1.00em;  padding: 5px; width: 100%; }\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinput[type=\"button\"], input[type=\"reset\"], input[type=\"submit\"] { height: auto; width: auto; cursor: pointer; box-shadow: 0px 0px 5px #0361A8; float: right; margin-top: 10px; }\r\n");
      out.write("\t\t\t\t\t\t\t\t\ttable.center { margin-left:auto; margin-right:auto; }\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.error { font-family: verdana,arial; color: #D41313; font-size: 1.00em; }\r\n");
      out.write("\t\t\t\t\t\t\t\t</style>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<center><font face='Verdana' size='2' color=green>Welcome ");
      out.print(n );
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<br><br><a href=update-profile.php>Update Profile</a> . <a href=change-password.php>Change Password</a> . <a href=logout.php>Logout</a></font></center><meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t\t\t  \t\t\t\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t\t  \t\t\t\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\t\t\t  \t\t\t\t\t<title>Download Buttons</title>\r\n");
      out.write("\t\t\t  \t\t\t\t\t<!--<link rel=\"stylesheet\" href=\"style.css\">\t\t\t\t\t\r\n");
      out.write("  \t\t\t\t\t\t\t\t-->\r\n");
      out.write("   \t\t\t\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t <script type=\"text/javascript\">             \r\n");
      out.write("\t\t\t\t\t\t\t\t         alert (\"Please download the key, and then create your Virtual Machine.\");\r\n");
      out.write("\t\t\t\t\t\t\t\t </script> \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t <a href=\"demo.private\" download=\"http://10.14.18.159/login/key.private\" class=\"button button-gray\">Download Key</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"iptable.php\"  class=\"button button-darkblue\">Create your Virtual Machine</a> \r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("     \t\t\t\t\t\t\t\t<input type=\"button\" onClick=\"location.href='template1.jsp'\" value=\"Next\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div><!-- end box sizing -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div><!-- end post -->\t\t\r\n");
      out.write("\t\t</div> <!-- end contentn -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"sidebar\">\r\n");
      out.write("\t\t\t<div id=\"about-box\">\r\n");
      out.write("\t\t\t\t<h2>About this Site</h2>\r\n");
      out.write("\t\t\t\t<p>This site is under development.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<h2>Categories</h2>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"first\"><a href=\"blue-login-box-html/login.html\">Login</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">About us</a></li>\r\n");
      out.write("\t\t\t\t\t\t<!--<li><a href=\"#\">Donec felis duis</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Eget tempus lorem</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Veroeros consequat</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Nullam blandit</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\">Tempus aliquam </a></li> -->\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<h2>Links</h2>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"first\"><a href=\"http://sit.iitkgp.ernet.in/~smisra/swan/index.html\">SWAN</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://sit.iitkgp.ernet.in/\">SIT</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://www.iitkgp.ac.in/\">IIT Kharagpur</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div><!-- end sidebar -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div style=\"clear: both;\">&nbsp;</div>\r\n");
      out.write("\t</div><!-- end bg -->\r\n");
      out.write("</div><!-- end page -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
