/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-07-24 07:59:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class relogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\r\n");
      out.write("\t<title>Login Box HTML Code - www.PSDGraphics.com</title>\r\n");
      out.write("\t\r\n");
      out.write("\t<link href=\"default.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link href=\"login-box.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\t<div id=\"logo\">\r\n");
      out.write("\t\t<h1><a href=\"#\">Sensor-cloud Infrastructure</a></h1>\r\n");
      out.write("\t\t<h2>By <a href=\"http://www.nodethirtythree.com/\">SIT, IIT, Kharagpur</a> <a href=\"http://www.freecsstemplates.org/\"></a></h2>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<marquee><b><font size = \"4\" color = \"red\" face=\"Lucida\"><i>Sensor-cloud: A paradigm shift from traditional WSNs</i></font></b></marquee>\r\n");
      out.write("\t<div id=\"menu\">\r\n");
      out.write("\t\t<ul>\r\n");
      out.write("\t\t\t<li class=\"active\"><a href=\"NewFile.jsp\" accesskey=\"1\" title=\"\">Home</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" accesskey=\"2\" title=\"\">Archives</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"#\" accesskey=\"3\" title=\"\">About</a></li>\r\n");
      out.write("\t\t\t<li><a href=\"contact.jsp\" accesskey=\"4\" title=\"\">Contact</a></li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"page\">\r\n");
      out.write("\t<div id=\"bg\">\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<div class=\"post\" style=\"padding-top: 57px;\">\r\n");
      out.write("\t\t\t\t<h2 class=\"title\">Welcome to Sensor-cloud Infrastructure Version 1.0!</h2>\r\n");
      out.write("\t\t\t\t<h3 class=\"date\">Thursday, May 25, 2014</h3>\r\n");
      out.write("\t\t\t\t<div class=\"entry\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<p><strong> Sensor-cloud Infrastructure </strong> is a unique sensor data storage, visualization and remote management platform that leverages powerful cloud computing\r\n");
      out.write("\t\t\t\t\ttechnologies to provide excellent data scalability, rapid visualization, and user programmable analysis. </p>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\talert(\"INCORRECT CREDENTIALS !! PLEASE TRY AGAIN. \");\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div style=\"padding: 00px 0 0 70px;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"login-box\">\t\r\n");
      out.write("\t\t\t\t\t\t<H2>Login</H2>\r\n");
      out.write("\t\t\t\t\t\tPlease login to avail of Sensors-as-a-Service\r\n");
      out.write("\t\t\t\t\t\t<br> </br>\r\n");
      out.write("\t\t\t\t\t\t<br> </br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<form action='loginchk.jsp' method=post>\r\n");
      out.write("\t\t\t\t\t\t\t<table border='0' cellspacing='0' cellpadding='0' align=center>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <tr id='cat'>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t<td > \r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t\t<font face='verdana, arial, helvetica' size='2' align='center'>  &nbsp;Login ID  &nbsp; &nbsp; </font>\r\n");
      out.write("\t\t\t\t\t\t\t\t  \t\t</td> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td  align='center'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<font face='verdana, arial, helvetica' size='2' > <input type ='text' class='bginput' name='userid' ></font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t  </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t  <tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td >\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<font face='verdana, arial, helvetica' size='2' align='center'>  &nbsp;Password  </font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td align='center'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<font face='verdana, arial, helvetica' size='2' ><input type ='password' class='bginput' name='password' ></font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t </tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t <tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t \t\t<td colspan='2' align='center'>\r\n");
      out.write("\t\t\t\t\t\t\t\t \t\t\t\t<font face='verdana, arial, helvetica' size='2' align='center'>  \r\n");
      out.write("\t\t\t\t\t\t\t\t\t \t\t\t\t<input type=\"image\" src=\"images/login.png\" alt=\"Submit details\" value='Submit'/> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t \t\t\t\t<input type=\"image\" src=\"images/submit.png\" alt=\"Submit details\" value='Submit'/>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"login-box-options\">\r\n");
      out.write("\t\t\t\t\t\t\t\t </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\t\t\t <tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t \t\t<td >\r\n");
      out.write("\t\t\t\t\t\t\t\t \t\t\t\t<font face='verdana, arial, helvetica' size='2' align='center'> &nbsp;<a href='http://10.14.18.159/login/signup.php'>New Member Sign UP</a></font></td> <td  align='center'><font face='verdana, arial, helvetica' size='2' ><a href=http://10.14.18.159/login/forgot-password.php>\tForgot Password?</a> </font>\r\n");
      out.write("\t\t\t\t\t\t\t\t \t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t <tr> \r\n");
      out.write("\t\t\t\t\t\t\t\t \t\t<td colspan='2' align='center'>\r\n");
      out.write("\t\t\t\t\t\t\t\t \t\t\t\t<font face='verdana, arial, helvetica' size='2' align='center'>&nbsp;</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t \t\t</td> \r\n");
      out.write("\t\t\t\t\t\t\t\t </tr> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t</center>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div> <!--  login-box -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div> <!-- entry -->\r\n");
      out.write("\t</div> <!-- post -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("</div> \t<!-- end contentn -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"sidebar\">\r\n");
      out.write("\t\t\t<div id=\"about-box\">\r\n");
      out.write("\t\t\t\t<h2>About this Site</h2>\r\n");
      out.write("\t\t\t\t<p>This site is under development.</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<h2>Links</h2>\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li class=\"first\"><a href=\"http://sit.iitkgp.ernet.in/~smisra/swan/index.html\">SWAN</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://sit.iitkgp.ernet.in/\">SIT</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"http://www.iitkgp.ac.in/\">IIT Kharagpur</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- end sidebar -->\r\n");
      out.write("\t\t<div style=\"clear: both;\">&nbsp;</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
