/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-10-27 06:13:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class sensorallocation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");

    String usershow = null;
    String userpg = null;
    String logshow = null;
    String logpg = null;
    
    if(session.getAttribute("userId") != null)
    {
        usershow = "Welcome " + session.getAttribute("userId").toString();
        userpg = "#";
        logshow = "Logoff";
        logpg = "logoff";
        //response.sendRedirect("login_aboutus.jsp");
    }
    else
    {
        usershow = "Register";
        userpg = "register";        
        logshow = "Login";
        logpg = "login";        
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t");
 
		String sensor_types = "";
		String region_types = "";
		String sensor_ids = "";
		int sensor_array_type[] = new int[100];
		int sensor_array_reg[] = new int[100];
		int vs_id = 0;
		//sensors = sensors + request.getParameter("sensor2") + request.getParameter("sensor3") + request.getParameter("sensor4");
		for (int i=1;i<=4;i++)
		{
			String inter_type = "sensor" + i;
			if(request.getParameter(inter_type)== null) 
				continue;
			sensor_types = sensor_types + request.getParameter(inter_type) + "," ;
			//sensor_array_type[i-1] = Integer.parseInt(request.getParameter(inter_type));
					
		}
		//sensor_types = sensor_types.substring(0, sensor_types.length()-1);
		System.out.println("Sensors: " + sensor_types);
		
		for (int i=1;i<=4;i++)
		{
			String inter_reg = "region" + i;
			if(request.getParameter(inter_reg)== null) 
				continue;
			region_types = region_types + request.getParameter(inter_reg) + "," ;
			//sensor_array_reg[i-1] = Integer.parseInt(request.getParameter(inter_reg));
					
		}
		region_types = region_types.substring(0, region_types.length()-1);
		System.out.println("Regionss: " + region_types);
		
		
		try {
			Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
			String url = "jdbc:odbc:Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=" + "C:\\Users\\user\\Desktop\\sensor-cloud.accdb";
            Connection conn = DriverManager.getConnection(url);
            Statement st = conn.createStatement();

            String sql1 = "SELECT SensorId from SensorMasterTable where TypeId in (" + sensor_types + ") and RegionId in (" + region_types + ");";
            System.out.println(sql1);
            ResultSet rs = st.executeQuery(sql1);
            while(rs.next())
            {    
            	int a = rs.getInt("SensorId");
            	sensor_ids = sensor_ids + a + ",";
            	//System.out.println("extracted sensor ids: " + a);                                  
            } 
            //sensor_ids = sensor_ids.substring(0, sensor_ids.length()-1);
            sensor_ids="11,12";
            System.out.println("extracted sensor id string: " + sensor_ids);    
            sql1 = "INSERT INTO VirtualSensorTable (VirtualSensorId, SensorIds, UserId) VALUES(-1, '" + sensor_ids + "'," + session.getAttribute("userId") + " );";
            System.out.println(sql1);
            st.execute(sql1);
            sql1 = "SELECT ID from VirtualSensorTable WHERE VirtualSensorId = -1;";
            rs = st.executeQuery(sql1);
            if(rs.next())
            {
            	vs_id = rs.getInt("ID");
            	
            }
            
            sql1 = "UPDATE VirtualSensorTable SET VirtualSensorId = ID WHERE VirtualSensorId = -1;";
            System.out.println(sql1);
            st.execute(sql1);
            
            //String selTable1 = "SELECT * from VirtualSensorTable;";
            /*ResultSet rs1 = st.executeQuery(selTable1);
            while(rs1.next())
            {    
            	System.out.println(rs1.getInt(1) + " : " + rs1.getInt(2) + " : " + rs1.getString(3) + ":" + rs1.getInt(4));                                  
            }*/
            
            response.sendRedirect("vs_activation.jsp?vs_id=" + vs_id );
            
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
